spring:
  application:
    name: RoadHaulage
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DB_NAME}
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format-sql: true
    hibernate:
      ddl-auto: update
    show-sql: true