spring:
  application:
    name: RoadHaulage
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DB_NAME}
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format-sql: false
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true